Revert "Remove redundant "std::move"s in return statements"
The build failed with

  error: call to deleted constructor of 'llvm::Error'

errors.

This reverts commit 30387b5a97a2853f2b99c41b3d06568349b52a5a.