Revert "[ADT] Support const-qualified unique_functions"
This reverts commit 9787642883655961ac481705c1ad9bffd0e6624f.

Breaks the build:

llvm/include/llvm/ADT/FunctionExtras.h:223:7: error: explicit template argument list not allowed
  223 |       Callbacks<CallableT, CalledAs, EnableIfTrivial<CallableT>>;