Revert "[LoopVectorizer] Inloop vector reductions"
This reverts commit 2a8e501ea461a05199bc6cc73a8b2e055473fc02. It breaks the build:

```
~/src/llvm-project/llvm/lib/Analysis/IVDescriptors.cpp:868:10: error: no viable conversion from returned value of type 'SmallVector<[...], 8>' to function return type 'SmallVector<[...], 4>'
  return ReductionOperations;
```