Temporarily revert "Add a facility to get system cache directory and use it in clangd"
This reverts commit f7aa14362f94dd9ce4cf64a8319792d8ebd2cac6.

As it broke building the unittests:

.../sources/llvm-project/llvm/unittests/Support/Path.cpp:334:5: error: use of undeclared identifier 'set'
    set(Value);
    ^
1 error generated.