Revert "ADT: SmallVector size/capacity use word-size integers when elements are small"
This reverts commit f7b2fa3ef3e46afb6f4fc97254912e58836cdf25.

clang-cmake-armv7-quick/llvm/llvm/lib/Support/SmallVector.cpp:81:22:
error: duplicate explicit instantiation of 'SmallVectorBase<unsigned int>'